/**
 * Sentinel Sovereign Crypto — FIPS-204 / ML-DSA-87 signing with worker pool.
 *
 * Architecture (Parallel Sovereignty build):
 *   ┌──────────────┐    postMessage    ┌──────────────┐
 *   │  Main thread │ ────────────────> │ 4 workers    │
 *   │  (event-loop)│ <──────────────── │ (sign here)  │
 *   └──────────────┘    base64 sig     └──────────────┘
 *
 * Why workers?
 *   ML-DSA-87 sign is ~3-5ms of single-thread CPU. Doing it inline on the
 *   Express event loop means every signing request blocks every other
 *   request behind it. With a 4-worker pool we get ~4x sign throughput
 *   AND the event loop is never blocked, so RPS-level latency stays flat.
 *
 * Canonicalization:
 *   bindContext() uses json-stable-stringify so signatures are reproducible
 *   across runtimes / platforms (key ordering deterministic). This is
 *   required for any third-party verifier to ever validate our seal.
 */

import { ml_dsa87 } from "@noble/post-quantum/ml-dsa.js";
import { Worker } from "node:worker_threads";
import { createHash, randomBytes } from "node:crypto";
import stableStringify from "json-stable-stringify";
import { logger } from "./logger";

/**
 * Worker pool size. Default 4 (local dev). In production set to match the
 * deployment's vCPU budget — the Fargate task definition pins this to 3
 * (2-vCPU task: 1 vCPU for the event loop + 3 sign workers, ~2x oversub
 * which is the empirical sweet spot for tail latency at 25c).
 */
const POOL_SIZE: number = (() => {
  const raw = process.env["SENTINEL_CRYPTO_POOL_SIZE"];
  if (!raw) return 4;
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 1 || n > 32) {
    throw new Error(
      `SENTINEL_CRYPTO_POOL_SIZE must be an integer in [1, 32], got: ${raw}`,
    );
  }
  return n;
})();

interface Keypair {
  readonly publicKey: Uint8Array;
  readonly secretKey: Uint8Array;
}

let cachedKeypair: Keypair | null = null;
let cachedFingerprint: string | null = null;

// ── Seed resolution ─────────────────────────────────────────────────────────
function resolveSeed(): Uint8Array {
  const raw = process.env["SENTINEL_SIGNING_SEED"]?.trim();

  if (raw) {
    if (/^[0-9a-fA-F]{64}$/.test(raw)) {
      return Uint8Array.from(Buffer.from(raw, "hex"));
    }
    if (/^[A-Za-z0-9+/=_-]+$/.test(raw)) {
      try {
        const normalized = raw.replace(/-/g, "+").replace(/_/g, "/");
        const buf = Buffer.from(normalized, "base64");
        if (buf.length >= 32) {
          if (buf.length > 32) {
            logger.info(
              { providedBytes: buf.length },
              "SENTINEL_SIGNING_SEED is base64 with >32 bytes; using first 32.",
            );
          }
          return Uint8Array.from(buf.subarray(0, 32));
        }
      } catch {
        // fall through to hash-based fallback (gated below)
      }
    }
    // Hash-derived fallback. Gated to avoid silently accepting weak passphrases:
    //   • require ≥ 32 input characters (rough proxy for ≥ 192 bits of entropy
    //     when humans use random tokens; arbitrary words still slip through, so
    //     we shout about it at error-level)
    //   • require explicit opt-in via SENTINEL_ALLOW_DERIVED_SEED=1
    const derivedAllowed = process.env["SENTINEL_ALLOW_DERIVED_SEED"] === "1";
    if (raw.length >= 32 && derivedAllowed) {
      logger.error(
        { inputChars: raw.length },
        "SENTINEL_SIGNING_SEED is not 64-char hex or base64; deriving via SHA-256 because SENTINEL_ALLOW_DERIVED_SEED=1. Prefer a 64-char hex or 32-byte base64 value generated by a CSPRNG.",
      );
      return Uint8Array.from(createHash("sha256").update(raw, "utf8").digest());
    }
    logger.warn(
      { inputChars: raw.length, derivedAllowed },
      "SENTINEL_SIGNING_SEED is set but not a 64-char hex or ≥32-byte base64 value — ignoring and generating ephemeral random seed. Public-key fingerprint will change on every restart.",
    );
    return Uint8Array.from(randomBytes(32));
  }

  logger.warn(
    "SENTINEL_SIGNING_SEED not set — generating ephemeral keypair. " +
      "Public-key fingerprint will change on every restart. " +
      "Set SENTINEL_SIGNING_SEED to a stable 64-char hex value for production.",
  );
  return Uint8Array.from(randomBytes(32));
}

function getKeypair(): Keypair {
  if (cachedKeypair) return cachedKeypair;
  const seed = resolveSeed();
  const kp = ml_dsa87.keygen(seed);
  cachedKeypair = { publicKey: kp.publicKey, secretKey: kp.secretKey };
  return cachedKeypair;
}

// ── Worker pool ─────────────────────────────────────────────────────────────
interface PendingSign {
  resolve: (signature: string) => void;
  reject: (err: Error) => void;
}

let workers: Worker[] = [];
let nextWorkerIdx = 0;
let nextRequestId = 0;
const pendingSigns = new Map<number, PendingSign>();
let poolInitialized = false;

function initWorkerPool(): void {
  if (poolInitialized) return;
  poolInitialized = true;

  const { secretKey } = getKeypair();
  // Resolve worker URL relative to the running bundle. After build, this
  // file is bundled into dist/index.mjs and the worker into
  // dist/lib/crypto-worker.mjs, so the relative path is "./lib/crypto-worker.mjs".
  const workerUrl = new URL("./lib/crypto-worker.mjs", import.meta.url);

  for (let i = 0; i < POOL_SIZE; i++) {
    const w = new Worker(workerUrl, {
      // Pass secret key bytes; structuredClone copies them into the worker.
      workerData: { secretKey: Buffer.from(secretKey) },
    });

    w.on("message", (msg: { id: number; signature?: string; error?: string }) => {
      const pending = pendingSigns.get(msg.id);
      if (!pending) return;
      pendingSigns.delete(msg.id);
      if (msg.error) {
        pending.reject(new Error(msg.error));
      } else if (msg.signature) {
        pending.resolve(msg.signature);
      } else {
        pending.reject(new Error("worker returned malformed response"));
      }
    });

    w.on("error", (err) => {
      logger.error({ err, workerIdx: i }, "crypto worker emitted error event");
    });

    w.on("exit", (code) => {
      if (code !== 0) {
        logger.error({ workerIdx: i, code }, "crypto worker exited unexpectedly");
      }
    });

    workers.push(w);
  }

  logger.info({ poolSize: POOL_SIZE }, "ML-DSA-87 signing worker pool ready");
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * SHA-256(publicKey) truncated to 8 bytes, colon-separated, uppercased.
 *   e.g. "7A:F3:9C:21:E4:8B:5D:62"
 */
export function getPublicKeyFingerprint(): string {
  if (cachedFingerprint) return cachedFingerprint;
  const { publicKey } = getKeypair();
  const digest = createHash("sha256").update(publicKey).digest();
  const bytes = digest.subarray(0, 8);
  cachedFingerprint = Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0").toUpperCase())
    .join(":");
  return cachedFingerprint;
}

/**
 * Build the canonical message bound to a specific service.
 *
 *   "<service>|<canonical-JSON(payload)>"
 *
 * Uses json-stable-stringify so key ordering is deterministic — required
 * for third-party verifiers to reproduce the exact byte sequence we signed.
 */
function bindContext(service: string, payload: unknown): Uint8Array {
  const canonical = stableStringify(payload) ?? "";
  const message = `${service}|${canonical}`;
  return new TextEncoder().encode(message);
}

/**
 * Sign a payload via the worker pool. Async — never blocks the event loop.
 * Returns a base64 signature string suitable for transport.
 */
export function signWithContext(service: string, payload: unknown): Promise<string> {
  initWorkerPool();
  const message = bindContext(service, payload);

  const id = nextRequestId++;
  const worker = workers[nextWorkerIdx]!;
  nextWorkerIdx = (nextWorkerIdx + 1) % POOL_SIZE;

  return new Promise<string>((resolve, reject) => {
    pendingSigns.set(id, { resolve, reject });
    worker.postMessage({ id, message });
  });
}

/**
 * Verify a signature against a payload + service binding.
 * Synchronous — runs in the main thread because verify is called rarely
 * (forensics, tests) and avoiding worker round-trip latency is preferable.
 */
export function verifyWithContext(
  service: string,
  payload: unknown,
  signatureBase64: string,
): boolean {
  try {
    const { publicKey } = getKeypair();
    const message = bindContext(service, payload);
    const sig = Uint8Array.from(Buffer.from(signatureBase64, "base64"));
    return ml_dsa87.verify(sig, message, publicKey);
  } catch {
    return false;
  }
}

/** Returns the public key as a base64 string for distribution. */
export function getPublicKeyBase64(): string {
  return Buffer.from(getKeypair().publicKey).toString("base64");
}

/** Graceful shutdown — terminate workers so the process can exit cleanly. */
export async function shutdownCryptoWorkers(): Promise<void> {
  await Promise.all(workers.map((w) => w.terminate()));
  workers = [];
  poolInitialized = false;
}

export const SENTINEL_ALGORITHM = "ML-DSA-87" as const;
export const SENTINEL_STANDARD = "FIPS-204" as const;
